name: Sync GitHub Org Secrets and Variables

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'DRY RUN'
        required: true
        default: true
      enable_cleanup:
        type: boolean
        description: '⚠️ DANGER: Check to clean up stale variables'
        required: true
        default: false

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  sync:
    runs-on: 
      group: ${{format('idp-{0}-gha-runner-group', inputs.environment)}}
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}
      ORG_NAME: "Sisal-Org" # Your organization name
    steps:
      
      - name: Generate WF token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_ACTION_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_ACTION_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check config files
        id: check-configs
        run: |
          echo "Checking for required configuration files..."
          if [ ! -f "variables.json" ]; then
            echo "❌ ERROR: Required file 'variables.json' was not found. Stopping workflow."
            exit 1
          fi
          echo "✅ Config file is present."

      - name: Sync Variables from variables.json
        run: |
          echo "### Syncing Variables ###"
          
          # If dry_run is true, simulate the changes
          if [ "${{ inputs.dry_run }}" == "true" ]; then
            echo "DRY RUN MODE: Checking which variables would be created or updated."
            
            # Get all remote variables once to avoid multiple API calls
            REMOTE_VARS=$(gh variable list --org "$ORG_NAME" --json name,value)

            jq -c '. | to_entries[]' variables.json | while read -r entry; do
              VAR_NAME=$(echo "$entry" | jq -r '.key')
              VAR_VALUE=$(echo "$entry" | jq -r '.value')
              
              # Check if the variable exists remotely
              REMOTE_VALUE=$(echo "$REMOTE_VARS" | jq -r --arg name "$VAR_NAME" '.[] | select(.name == $name) | .value')

              if [ -z "$REMOTE_VALUE" ]; then
                echo "DRY RUN: Would CREATE variable '$VAR_NAME'"
              elif [ "$VAR_VALUE" != "$REMOTE_VALUE" ]; then
                echo "DRY RUN: Would UPDATE variable '$VAR_NAME' (values differ)"
              else
                echo "DRY RUN: Variable '$VAR_NAME' is already up to date."
              fi
            done
          
          # Otherwise, apply the changes
          else
            echo "APPLY MODE: Creating or updating variables."
            jq -c '. | to_entries[]' variables.json | while read -r entry; do
              VAR_NAME=$(echo "$entry" | jq -r '.key')
              VAR_VALUE=$(echo "$entry" | jq -r '.value')
              echo "🔧 Syncing organization variable: $VAR_NAME"
              gh variable set "$VAR_NAME" --body "$VAR_VALUE" --org "$ORG_NAME"
            done
            echo "✅ All variables have been synced successfully."
          fi

  cleanup-stale-items:
    if: ${{ inputs.enable_cleanup == true }}
    needs: sync
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.ORG_PAT }}
      ORG_NAME: "GamiHealth" # Your organization name
    steps:

      - name: Generate WF token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_ACTION_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_ACTION_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup Stale Organization Variables
        run: |
          echo "### Starting Variable Cleanup ###"
          
          LOCAL_VARS=$(jq -r 'keys | .[]' variables.json | sort)
          REMOTE_VARS=$(gh variable list --org "$ORG_NAME" --json name -q '.[].name' | sort)
          STALE_VARS=$(comm -13 <(echo "$LOCAL_VARS") <(echo "$REMOTE_VARS"))

          if [ -z "$STALE_VARS" ]; then
            echo "✅ No stale variables found. All good!"
            exit 0
          fi

          echo "Found the following stale variables to be deleted:"
          echo "$STALE_VARS"
          
          STALE_COUNT=$(echo "$STALE_VARS" | wc -l)
          if [ "$STALE_COUNT" -gt 5 ]; then
            echo "❌ SAFETY NET: Attempting to delete $STALE_COUNT variables, which is over the threshold of 5. Aborting."
            exit 1
          fi

          if [ "${{ inputs.dry_run }}" == "true" ]; then
            echo "DRY RUN: Would have deleted the variables listed above. No changes made."
          else
            echo "APPLY MODE: Deleting stale variables..."
            echo "$STALE_VARS" | while read -r variable; do
              gh variable delete "$variable" --org "$ORG_NAME"
              echo "Deleted variable: $variable"
            done
            echo "✅ Cleanup complete."
          fi