name: Sync GitHub Org Secrets and Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      delete_missing:
        type: boolean
        description: "Delete secrets and variables not present in config files?"
        required: false
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        ## NOT NEEDED ON SISAL
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Check config files
        id: check-configs
        run: |
          echo "Checking config files..."
          VAR_FILE="variables.json"
          SECRETS_FILE="secrets.json"
          if [ ! -f "$VAR_FILE"  || ! -f "$SECRETS_FILE" ]; then
            echo "❌ one config file was not found. Stopping ..."
            exit 1
          fi

      - name: Sync Variables from variables.json
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        run: |
          echo "Reading variables from variables.json"

          # Use jq to iterate over each key-value pair.
          jq -c '. | to_entries[]' variables.json | while read -r entry; do
            # Extract the variable name and value from the JSON entry.
            VAR_NAME=$(echo "$entry" | jq -r '.key')
            VAR_VALUE=$(echo "$entry" | jq -r '.value')

            echo "🔧 Syncing organization variable: $VAR_NAME"

            # Use 'gh variable set' to create or update the variable.
            # It handles the API calls automatically.
            # The --org flag targets organization variables.
            gh variable set "$VAR_NAME" --body "$VAR_VALUE" --org "GamiHealth"
          done

          echo "✅ All variables have been synced successfully."

      - name: Sync Secrets from secrets.json
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
        run: |
          echo "Reading secrets from secrets.json"

          # Use jq to iterate over each key-value pair in the JSON file.
          jq -c '. | to_entries[]' secrets.json | while read -r entry; do
            # Extract the secret name and value from the JSON entry.
            SECRET_NAME=$(echo "$entry" | jq -r '.key')
            SECRET_VALUE=$(echo "$entry" | jq -r '.value')

            echo "🔐 Syncing organization secret: $SECRET_NAME"

            # Use 'gh secret set' to create or update the secret.
            # It handles encryption and API calls automatically.
            # The value is piped to prevent it from appearing in shell history.
            # The --org flag targets organization secrets.
            echo "$SECRET_VALUE" | gh secret set "$SECRET_NAME" --org "GamiHealth" --body -
          done

          echo "✅ All secrets have been synced successfully."


      # - name: Sync Secrets from config.json
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
      #     ORG: GamiHealth
      #   run: |
      #     HEADERS: '-H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"'
      #     echo "Reading secrets from config.json"
      #     jq -c '.secrets | to_entries[]' config.json | while read -r entry; do
      #       SECRET=$(echo "$entry" | jq -r '.key')
      #       VALUE=$(echo "$entry" | jq -r '.value')
      #       echo "🔒 SECRET: $SECRET = $VALUE"
      #     done

      # - name: Sync Variables
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
      #     ORG: GamiHealth
      #     DELETE_MISSING: ${{ github.event.inputs.delete_missing }}
      #     HEADERS: '-H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28"'
      #   run: |
      #     printenv
      #     echo "🔁 Syncing variables..."
      #     CURRENT_VARS=$(curl -s $HEADERS \
      #       https://api.github.com/orgs/GamiHealth/actions/variables | jq -r '.variables // [] | .[].name')
      #     echo "Current VARS already present in Organization: $CURRENT_VARS"

      #     jq -c '.variables | to_entries[]' $CONFIG_FILE | while read -r entry; do
      #       VAR=$(echo "$entry" | jq -r '.key')
      #       VALUE=$(echo "$entry" | jq -r '.value')

      #       echo "➡️ Syncing variable: $VAR"

      #       RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEADERS \
      #         https://api.github.com/orgs/GamiHealth/actions/variables/$VAR)

      #       BODY=$(jq -n --arg name "$VAR" --arg value "$VALUE" '{name: $name, value: $value}')

      #       if [ "$RESPONSE" = "200" ]; then
      #         echo "✏️ Updating $VAR"
      #         curl -s -X PATCH $HEADERS -d "$BODY" \
      #           https://api.github.com/orgs/GamiHealth/actions/variables/$VAR
      #       else
      #         echo "🆕 Creating $VAR"
      #         curl -s -X POST $HEADERS -d "$BODY" \
      #           https://api.github.com/orgs/GamiHealth/actions/variables
      #       fi
      #     done


          # # Create/Update variables
          # for VAR in $(yq e -o=json '.variables | keys | .[]' config.yaml); do
          #   VALUE=$(yq e -o=json ".variables[\"$VAR\"]" config.yaml)
          #   echo "Trying to create/update VAR: $VAR with VALUE: $VALUE"

          #   # Check if variable exists
          #   HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          #     -H "Authorization: Bearer $GITHUB_TOKEN" \
          #     -H "Accept: application/vnd.github+json"
          #     -H "X-GitHub-Api-Version: 2022-11-28" \
          #     https://api.github.com/orgs/GamiHealth/actions/variables/$VAR)

          #   if [ "$HTTP_STATUS" -eq 200 ]; then
          #     echo "✏️ Updating variable: $VAR"
          #     curl -s -X PATCH \
          #       -H "Authorization: Bearer $GITHUB_TOKEN" \
          #       -H "Accept: application/vnd.github+json" \
          #       -H "X-GitHub-Api-Version: 2022-11-28" \
          #       https://api.github.com/orgs/GamiHealth/actions/variables/$VAR \
          #       -d '{"name":"$VAR","value":"$VALUE","visibility":"all"}'
          #   elif [ "$HTTP_STATUS" -eq 404 ]; then
          #     echo "🆕 Creating variable: $VAR"
          #     curl -s -X POST \
          #       -H "Authorization: Bearer $GITHUB_TOKEN" \
          #       -H "Accept: application/vnd.github+json" \
          #       -H "X-GitHub-Api-Version: 2022-11-28" \
          #       https://api.github.com/orgs/GamiHealth/actions/variables \
          #       -d '{"name":"$VAR","value":"$VALUE","visibility":"all"}'
          #   else
          #     echo "❌ Error checking variable $VAR (HTTP $HTTP_STATUS)"
          #   fi
          # done

      # - name: Sync Secrets
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
      #     ORG: GamiHealth
      #     DELETE_MISSING: ${{ github.event.inputs.delete_missing }}
      #   run: |
      #     echo "🔄 Syncing Secrets..."
      #     # Get public key for encryption
      #     PUBKEY_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      #       https://api.github.com/orgs/GamiHealth/actions/secrets/public-key)
      #     PUBKEY=$(echo "$PUBKEY_JSON" | jq -r '.key')
      #     KEY_ID=$(echo "$PUBKEY_JSON" | jq -r '.key_id')

      #     # Get current secrets
      #     CURRENT_SECRETS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      #       https://api.github.com/orgs/GamiHealth/actions/secrets | \
      #       jq -r '.secrets // [] | .[].name')


      #     # Create/Update secrets
      #     for SECRET in $(yq e -o=json '.secrets | keys | .[]' config.yaml); do
      #       VALUE=$(yq e -o=json ".secrets[\"$SECRET\"]" config.yaml)
      #       ENCRYPTED=$(echo -n "$VALUE" | \
      #         openssl pkeyutl -encrypt -pubin -inkey <(echo "$PUBKEY" | base64 -d) -pkeyopt rsa_padding_mode:pkcs1 | base64 -w0)
      #       echo "🟢 Creating/Updating secret: $SECRET"
      #       curl -s -X PUT \
      #         -H "Authorization: token $GITHUB_TOKEN" \
      #         -H "Accept: application/vnd.github+json" \
      #         https://api.github.com/orgs/GamiHealth/actions/secrets/$SECRET \
      #         -d "{\"encrypted_value\":\"$ENCRYPTED\", \"key_id\":\"$KEY_ID\"}"
      #     done
