name: Sync GitHub Org Secrets and Variables

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Setup jq
        run: sudo apt-get install jq -y

      - name: Read config file and sync
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}
          ORG_NAME: GamiHealth
        run: |
          CONFIG_FILE="config.yaml"

          # Sync Variables
          for VAR in $(yq e '.variables | keys | .[]' $CONFIG_FILE); do
            VALUE=$(yq e ".variables[\"$VAR\"]" $CONFIG_FILE)
            echo "Syncing variable: $VAR"
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/orgs/$ORG_NAME/actions/variables/$VAR \
              -d "{\"name\":\"$VAR\", \"value\":\"$VALUE\"}"
          done

          # Sync Secrets (encrypted with org public key)
          PUBKEY_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/orgs/$ORG_NAME/actions/secrets/public-key)
          PUBKEY=$(echo "$PUBKEY_JSON" | jq -r '.key')
          KEY_ID=$(echo "$PUBKEY_JSON" | jq -r '.key_id')

          for SECRET in $(yq e '.secrets | keys | .[]' $CONFIG_FILE); do
            VALUE=$(yq e ".secrets[\"$SECRET\"]" $CONFIG_FILE)
            # Encrypt secret value
            ENCRYPTED=$(echo -n "$VALUE" | openssl rsautl -encrypt -pubin -inkey <(echo "$PUBKEY") | base64 | tr -d '\n')
            echo "Syncing secret: $SECRET"
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/orgs/$ORG_NAME/actions/secrets/$SECRET \
              -d "{\"encrypted_value\":\"$ENCRYPTED\", \"key_id\":\"$KEY_ID\"}"
          done
